###
POST http://localhost:8080/api/register
Content-Type: application/x-www-form-urlencoded

nom=te111st3&prenom=tot111o3&numTel=1234&email=eje11113&mdp=123

###
GET http://localhost:8080/api/test

###
GET http://localhost:8080/api/utilisateur/employee
Authorization: Basic employee pass


###
GET http://localhost:8080/api/utilisateur/3/monFrigo


###
GET http://localhost:8080/api/utilisateur/3/achats


###
PUT http://localhost:8080/api/utilisateur/4/mdp
Content-Type: application/x-www-form-urlencoded

ancienMdp=123&nouveauMdp=1234


###
POST http://localhost:8080/api/utilisateur/employee/ajouterProduit
Authorization: Basic employee pass
Content-Type: application/json

{
  "referenceProduit": "125548",
  "nomProduit": "pates",
  "description": "pâtes",
  "dlc": "22/04/2022",
  "quantite": 1
}


###
GET http://localhost:8080/api/utilisateur/employee/ajouterProduit
Authorization: Basic employee pass







