###
POST http://localhost:8080/api/register
Content-Type: application/x-www-form-urlencoded

nom=test3&prenom=toto3&role=u&numTel=1234&email=eje13&mdp=123

###
GET http://localhost:8080/api/test

###
GET http://localhost:8080/api/utilisateur/1


###
GET http://localhost:8080/api/utilisateur/3/monFrigo


###
GET http://localhost:8080/api/utilisateur/3/achats


###
PUT http://localhost:8080/api/utilisateur/4/mdp
Content-Type: application/x-www-form-urlencoded

ancienMdp=123&nouveauMdp=1234
