###
POST http://localhost:8080/api/register
Content-Type: application/x-www-form-urlencoded

username=jean&nom=te111st3&prenom=tot111o3&numTel=1234&email=eje11144413&motDePasse=pass

###
GET http://localhost:8080/api/test

###
GET http://localhost:8080/api/utilisateur/employee
Authorization: Basic employee pass


###
GET http://localhost:8080/api/utilisateur/jean
Authorization: Basic jean pass

###
GET http://localhost:8080/api/utilisateur/3/monFrigo


###
GET http://localhost:8080/api/utilisateur/3/achats


###
PUT http://localhost:8080/api/utilisateur/jean/mdp
Authorization: Basic jean pass
Content-Type: application/x-www-form-urlencoded

nouveauMdp=1234


###
POST http://localhost:8080/api/utilisateur/employee/ajouterProduit
Authorization: Basic employee pass
Content-Type: application/json

{
  "referenceProduit": "125548",
  "nomProduit": "pates",
  "description": "pâtes",
  "dlc": "22/04/2022",
  "quantite": 1
}


###
GET http://localhost:8080/api/utilisateur/employee/ajouterProduit
Authorization: Basic employee pass







